# Generated by Django 5.2.7 on 2025-10-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreationrequest',
            old_name='rejected_reason',
            new_name='rejection_reason',
        ),
    ]
