# Generated by Django 5.2.7 on 2025-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_personaldetail_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
